version: '2.2'

services:
  prometheus:
    image: prom/prometheus
    depends_on:
      geth:
        condition: service_started
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:80"
    depends_on:
      prometheus:
        condition: service_started
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db
